fix: Update the release process
googleapis/google-cloudevents-java pull request #141
Opened 2023-02-01 20:01 UTC by averikitsch

[go/java-cloud-library-playbook](https://goto.google.com/java-cloud-library-playbook) mentions Java needs:
* the release trigger app
* kokoro release configs. 

The label "autorelease: published" gets added by the release trigger app.

2023-02-02 00:39 UTC, chingor13 requested changes
Can you ensure that the .sh files are in executable mode as well?

2023-02-02 00:39 UTC, chingor13 commented on .kokoro/release/stage.sh
> +python3 -m releasetool publish-reporter-script > /tmp/publisher-script; source /tmp/publisher-script
This file looks out of date. We require loading from a lockfile. example: https://github.com/googleapis/google-http-java-client/blob/0664e1744e0885a1cb8787481ccfbab0de845fe9/.kokoro/release/stage.sh#L19-L21

2023-02-02 02:34 UTC, meltsufin commented on .kokoro/linkage-monitor.sh
> +JAR=linkage-monitor-latest-all-deps.jar
Do you really need the linkage-monitor?

2023-02-02 04:11 UTC, suztomo commented on .kokoro/linkage-monitor.sh
> +JAR=linkage-monitor-latest-all-deps.jar
No.

2023-02-02 20:49 UTC, averikitsch commented
@chingor13 can you rereview? I've pulled a new copy of the Kokoro release files and have filed an issue to explore Owlbot in the future #142

2023-02-03 17:19 UTC, chingor13 approved these changes

2023-02-03 18:46 UTC, muncus approved these changes

2023-02-03 18:57 UTC, merged